<?php

namespace Database\Seeders\Tahfidz;

use App\Models\TahfidzSurah;
use Illuminate\Database\Seeder;

class TahfidzSurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            ['number' => 1, 'name' => 'Al-Fatihah', 'name_arabic' => 'الفاتحة', 'verses_count' => 7, 'juz' => '1'],
            ['number' => 2, 'name' => 'Al-Baqarah', 'name_arabic' => 'البقرة', 'verses_count' => 286, 'juz' => '1-3'],
            ['number' => 3, 'name' => "Ali 'Imran", 'name_arabic' => 'آل عمران', 'verses_count' => 200, 'juz' => '3-4'],
            ['number' => 4, 'name' => 'An-Nisa', 'name_arabic' => 'النساء', 'verses_count' => 176, 'juz' => '4-6'],
            ['number' => 5, 'name' => 'Al-Maidah', 'name_arabic' => 'المائدة', 'verses_count' => 120, 'juz' => '6-7'],
            ['number' => 6, 'name' => "Al-An'am", 'name_arabic' => 'الأنعام', 'verses_count' => 165, 'juz' => '7-8'],
            ['number' => 7, 'name' => "Al-A'raf", 'name_arabic' => 'الأعراف', 'verses_count' => 206, 'juz' => '8-9'],
            ['number' => 8, 'name' => 'Al-Anfal', 'name_arabic' => 'الأنفال', 'verses_count' => 75, 'juz' => '9-10'],
            ['number' => 9, 'name' => 'At-Taubah', 'name_arabic' => 'التوبة', 'verses_count' => 129, 'juz' => '10-11'],
            ['number' => 10, 'name' => 'Yunus', 'name_arabic' => 'يونس', 'verses_count' => 109, 'juz' => '11'],
            ['number' => 11, 'name' => 'Hud', 'name_arabic' => 'هود', 'verses_count' => 123, 'juz' => '11-12'],
            ['number' => 12, 'name' => 'Yusuf', 'name_arabic' => 'يوسف', 'verses_count' => 111, 'juz' => '12-13'],
            ['number' => 13, 'name' => "Ar-Ra'd", 'name_arabic' => 'الرعد', 'verses_count' => 43, 'juz' => '13'],
            ['number' => 14, 'name' => 'Ibrahim', 'name_arabic' => 'إبراهيم', 'verses_count' => 52, 'juz' => '13'],
            ['number' => 15, 'name' => 'Al-Hijr', 'name_arabic' => 'الحجر', 'verses_count' => 99, 'juz' => '14'],
            ['number' => 16, 'name' => 'An-Nahl', 'name_arabic' => 'النحل', 'verses_count' => 128, 'juz' => '14'],
            ['number' => 17, 'name' => "Al-Isra'", 'name_arabic' => 'الإسراء', 'verses_count' => 111, 'juz' => '15'],
            ['number' => 18, 'name' => 'Al-Kahf', 'name_arabic' => 'الكهف', 'verses_count' => 110, 'juz' => '15-16'],
            ['number' => 19, 'name' => 'Maryam', 'name_arabic' => 'مريم', 'verses_count' => 98, 'juz' => '16'],
            ['number' => 20, 'name' => 'Ta Ha', 'name_arabic' => 'طه', 'verses_count' => 135, 'juz' => '16'],
            ['number' => 21, 'name' => 'Al-Anbiya', 'name_arabic' => 'الأنبياء', 'verses_count' => 112, 'juz' => '17'],
            ['number' => 22, 'name' => 'Al-Hajj', 'name_arabic' => 'الحج', 'verses_count' => 78, 'juz' => '17'],
            ['number' => 23, 'name' => "Al-Mu'minun", 'name_arabic' => 'المؤمنون', 'verses_count' => 118, 'juz' => '18'],
            ['number' => 24, 'name' => 'An-Nur', 'name_arabic' => 'النور', 'verses_count' => 64, 'juz' => '18'],
            ['number' => 25, 'name' => 'Al-Furqan', 'name_arabic' => 'الفرقان', 'verses_count' => 77, 'juz' => '19'],
            ['number' => 26, 'name' => "Ash-Shu'ara", 'name_arabic' => 'الشعراء', 'verses_count' => 227, 'juz' => '19'],
            ['number' => 27, 'name' => 'An-Naml', 'name_arabic' => 'النمل', 'verses_count' => 93, 'juz' => '19-20'],
            ['number' => 28, 'name' => 'Al-Qasas', 'name_arabic' => 'القصص', 'verses_count' => 88, 'juz' => '20'],
            ['number' => 29, 'name' => 'Al-Ankabut', 'name_arabic' => 'العنكبوت', 'verses_count' => 69, 'juz' => '20-21'],
            ['number' => 30, 'name' => 'Ar-Rum', 'name_arabic' => 'الروم', 'verses_count' => 60, 'juz' => '21'],
            ['number' => 31, 'name' => 'Luqman', 'name_arabic' => 'لقمان', 'verses_count' => 34, 'juz' => '21'],
            ['number' => 32, 'name' => 'As-Sajdah', 'name_arabic' => 'السجدة', 'verses_count' => 30, 'juz' => '21'],
            ['number' => 33, 'name' => 'Al-Ahzab', 'name_arabic' => 'الأحزاب', 'verses_count' => 73, 'juz' => '21-22'],
            ['number' => 34, 'name' => 'Saba', 'name_arabic' => 'سبإ', 'verses_count' => 54, 'juz' => '22'],
            ['number' => 35, 'name' => 'Fatir', 'name_arabic' => 'فاطر', 'verses_count' => 45, 'juz' => '22'],
            ['number' => 36, 'name' => 'Ya Sin', 'name_arabic' => 'يس', 'verses_count' => 83, 'juz' => '22-23'],
            ['number' => 37, 'name' => 'As-Saffat', 'name_arabic' => 'الصافات', 'verses_count' => 182, 'juz' => '23'],
            ['number' => 38, 'name' => 'Sad', 'name_arabic' => 'ص', 'verses_count' => 88, 'juz' => '23'],
            ['number' => 39, 'name' => 'Az-Zumar', 'name_arabic' => 'الزمر', 'verses_count' => 75, 'juz' => '23-24'],
            ['number' => 40, 'name' => 'Ghafir', 'name_arabic' => 'غافر', 'verses_count' => 85, 'juz' => '24'],
            ['number' => 41, 'name' => 'Fussilat', 'name_arabic' => 'فصلت', 'verses_count' => 54, 'juz' => '24-25'],
            ['number' => 42, 'name' => 'Ash-Shura', 'name_arabic' => 'الشورى', 'verses_count' => 53, 'juz' => '25'],
            ['number' => 43, 'name' => 'Az-Zukhruf', 'name_arabic' => 'الزخرف', 'verses_count' => 89, 'juz' => '25'],
            ['number' => 44, 'name' => 'Ad-Dukhan', 'name_arabic' => 'الدخان', 'verses_count' => 59, 'juz' => '25'],
            ['number' => 45, 'name' => 'Al-Jasiyah', 'name_arabic' => 'الجاثية', 'verses_count' => 37, 'juz' => '25'],
            ['number' => 46, 'name' => 'Al-Ahqaf', 'name_arabic' => 'الأحقاف', 'verses_count' => 35, 'juz' => '26'],
            ['number' => 47, 'name' => 'Muhammad', 'name_arabic' => 'محمد', 'verses_count' => 38, 'juz' => '26'],
            ['number' => 48, 'name' => 'Al-Fath', 'name_arabic' => 'الفتح', 'verses_count' => 29, 'juz' => '26'],
            ['number' => 49, 'name' => 'Al-Hujurat', 'name_arabic' => 'الحجرات', 'verses_count' => 18, 'juz' => '26'],
            ['number' => 50, 'name' => 'Qaf', 'name_arabic' => 'ق', 'verses_count' => 45, 'juz' => '26'],
            ['number' => 51, 'name' => 'Az-Zariyat', 'name_arabic' => 'الذاريات', 'verses_count' => 60, 'juz' => '27'],
            ['number' => 52, 'name' => 'At-Tur', 'name_arabic' => 'الطور', 'verses_count' => 49, 'juz' => '27'],
            ['number' => 53, 'name' => 'An-Najm', 'name_arabic' => 'النجم', 'verses_count' => 62, 'juz' => '27'],
            ['number' => 54, 'name' => 'Al-Qamar', 'name_arabic' => 'القمر', 'verses_count' => 55, 'juz' => '27'],
            ['number' => 55, 'name' => 'Ar-Rahman', 'name_arabic' => 'الرحمن', 'verses_count' => 78, 'juz' => '27'],
            ['number' => 56, 'name' => "Al-Waqi'ah", 'name_arabic' => 'الواقعة', 'verses_count' => 96, 'juz' => '27'],
            ['number' => 57, 'name' => 'Al-Hadid', 'name_arabic' => 'الحديد', 'verses_count' => 29, 'juz' => '27'],
            ['number' => 58, 'name' => 'Al-Mujadilah', 'name_arabic' => 'المجادلة', 'verses_count' => 22, 'juz' => '28'],
            ['number' => 59, 'name' => 'Al-Hasyr', 'name_arabic' => 'الحشر', 'verses_count' => 24, 'juz' => '28'],
            ['number' => 60, 'name' => 'Al-Mumtahanah', 'name_arabic' => 'الممتحنة', 'verses_count' => 13, 'juz' => '28'],
            ['number' => 61, 'name' => 'As-Saff', 'name_arabic' => 'الصف', 'verses_count' => 14, 'juz' => '28'],
            ['number' => 62, 'name' => "Al-Jumu'ah", 'name_arabic' => 'الجمعة', 'verses_count' => 11, 'juz' => '28'],
            ['number' => 63, 'name' => 'Al-Munafiqun', 'name_arabic' => 'المنافقون', 'verses_count' => 11, 'juz' => '28'],
            ['number' => 64, 'name' => 'At-Taghabun', 'name_arabic' => 'التغابن', 'verses_count' => 18, 'juz' => '28'],
            ['number' => 65, 'name' => 'At-Talaq', 'name_arabic' => 'الطلاق', 'verses_count' => 12, 'juz' => '28'],
            ['number' => 66, 'name' => 'At-Tahrim', 'name_arabic' => 'التحريم', 'verses_count' => 12, 'juz' => '28'],
            ['number' => 67, 'name' => 'Al-Mulk', 'name_arabic' => 'الملك', 'verses_count' => 30, 'juz' => '29'],
            ['number' => 68, 'name' => 'Al-Qalam', 'name_arabic' => 'القلم', 'verses_count' => 52, 'juz' => '29'],
            ['number' => 69, 'name' => 'Al-Haqqah', 'name_arabic' => 'الحاقة', 'verses_count' => 52, 'juz' => '29'],
            ['number' => 70, 'name' => "Al-Ma'arij", 'name_arabic' => 'المعارج', 'verses_count' => 44, 'juz' => '29'],
            ['number' => 71, 'name' => 'Nuh', 'name_arabic' => 'نوح', 'verses_count' => 28, 'juz' => '29'],
            ['number' => 72, 'name' => 'Al-Jinn', 'name_arabic' => 'الجن', 'verses_count' => 28, 'juz' => '29'],
            ['number' => 73, 'name' => 'Al-Muzzammil', 'name_arabic' => 'المزمل', 'verses_count' => 20, 'juz' => '29'],
            ['number' => 74, 'name' => 'Al-Muddassir', 'name_arabic' => 'المدثر', 'verses_count' => 56, 'juz' => '29'],
            ['number' => 75, 'name' => 'Al-Qiyamah', 'name_arabic' => 'القيامة', 'verses_count' => 40, 'juz' => '29'],
            ['number' => 76, 'name' => 'Al-Insan', 'name_arabic' => 'الانسان', 'verses_count' => 31, 'juz' => '29'],
            ['number' => 77, 'name' => 'Al-Mursalat', 'name_arabic' => 'المرسلات', 'verses_count' => 50, 'juz' => '29'],
            ['number' => 78, 'name' => "An-Naba'", 'name_arabic' => 'النبإ', 'verses_count' => 40, 'juz' => '30'],
            ['number' => 79, 'name' => "An-Nazi'at", 'name_arabic' => 'النازعات', 'verses_count' => 46, 'juz' => '30'],
            ['number' => 80, 'name' => "'Abasa", 'name_arabic' => 'عبس', 'verses_count' => 42, 'juz' => '30'],
            ['number' => 81, 'name' => 'At-Takwir', 'name_arabic' => 'التكوير', 'verses_count' => 29, 'juz' => '30'],
            ['number' => 82, 'name' => 'Al-Infitar', 'name_arabic' => 'الإنفطار', 'verses_count' => 19, 'juz' => '30'],
            ['number' => 83, 'name' => 'Al-Mutaffifin', 'name_arabic' => 'المطففين', 'verses_count' => 36, 'juz' => '30'],
            ['number' => 84, 'name' => 'Al-Insyiqaq', 'name_arabic' => 'الإنشقاق', 'verses_count' => 25, 'juz' => '30'],
            ['number' => 85, 'name' => 'Al-Buruj', 'name_arabic' => 'البروج', 'verses_count' => 22, 'juz' => '30'],
            ['number' => 86, 'name' => 'At-Tariq', 'name_arabic' => 'الطارق', 'verses_count' => 17, 'juz' => '30'],
            ['number' => 87, 'name' => "Al-A'la", 'name_arabic' => 'الأعلى', 'verses_count' => 19, 'juz' => '30'],
            ['number' => 88, 'name' => 'Al-Gasyiyah', 'name_arabic' => 'الغاشية', 'verses_count' => 26, 'juz' => '30'],
            ['number' => 89, 'name' => 'Al-Fajr', 'name_arabic' => 'الفجر', 'verses_count' => 30, 'juz' => '30'],
            ['number' => 90, 'name' => 'Al-Balad', 'name_arabic' => 'البلد', 'verses_count' => 20, 'juz' => '30'],
            ['number' => 91, 'name' => 'Asy-Syams', 'name_arabic' => 'الشمس', 'verses_count' => 15, 'juz' => '30'],
            ['number' => 92, 'name' => 'Al-Lail', 'name_arabic' => 'الليل', 'verses_count' => 21, 'juz' => '30'],
            ['number' => 93, 'name' => 'Ad-Duha', 'name_arabic' => 'الضحى', 'verses_count' => 11, 'juz' => '30'],
            ['number' => 94, 'name' => 'Al-Insyirah', 'name_arabic' => 'الشرح', 'verses_count' => 8, 'juz' => '30'],
            ['number' => 95, 'name' => 'At-Tin', 'name_arabic' => 'التين', 'verses_count' => 8, 'juz' => '30'],
            ['number' => 96, 'name' => "Al-'Alaq", 'name_arabic' => 'العلق', 'verses_count' => 19, 'juz' => '30'],
            ['number' => 97, 'name' => 'Al-Qadr', 'name_arabic' => 'القدر', 'verses_count' => 5, 'juz' => '30'],
            ['number' => 98, 'name' => 'Al-Bayyinah', 'name_arabic' => 'البينة', 'verses_count' => 8, 'juz' => '30'],
            ['number' => 99, 'name' => 'Az-Zalzalah', 'name_arabic' => 'الزلزلة', 'verses_count' => 8, 'juz' => '30'],
            ['number' => 100, 'name' => "Al-'Adiyat", 'name_arabic' => 'العاديات', 'verses_count' => 11, 'juz' => '30'],
            ['number' => 101, 'name' => 'Al-Qari\'ah', 'name_arabic' => 'القارعة', 'verses_count' => 11, 'juz' => '30'],
            ['number' => 102, 'name' => 'At-Takasur', 'name_arabic' => 'التكاثر', 'verses_count' => 8, 'juz' => '30'],
            ['number' => 103, 'name' => "Al-'Asr", 'name_arabic' => 'العصر', 'verses_count' => 3, 'juz' => '30'],
            ['number' => 104, 'name' => 'Al-Humazah', 'name_arabic' => 'الهمزة', 'verses_count' => 9, 'juz' => '30'],
            ['number' => 105, 'name' => 'Al-Fil', 'name_arabic' => 'الفيل', 'verses_count' => 5, 'juz' => '30'],
            ['number' => 106, 'name' => 'Quraisy', 'name_arabic' => 'قريش', 'verses_count' => 4, 'juz' => '30'],
            ['number' => 107, 'name' => "Al-Ma'un", 'name_arabic' => 'الماعون', 'verses_count' => 7, 'juz' => '30'],
            ['number' => 108, 'name' => 'Al-Kausar', 'name_arabic' => 'الكوثر', 'verses_count' => 3, 'juz' => '30'],
            ['number' => 109, 'name' => 'Al-Kafirun', 'name_arabic' => 'الكافرون', 'verses_count' => 6, 'juz' => '30'],
            ['number' => 110, 'name' => 'An-Nasr', 'name_arabic' => 'النصر', 'verses_count' => 3, 'juz' => '30'],
            ['number' => 111, 'name' => 'Al-Lahab', 'name_arabic' => 'المسد', 'verses_count' => 5, 'juz' => '30'],
            ['number' => 112, 'name' => 'Al-Ikhlas', 'name_arabic' => 'الإخلاص', 'verses_count' => 4, 'juz' => '30'],
            ['number' => 113, 'name' => 'Al-Falaq', 'name_arabic' => 'الفلق', 'verses_count' => 5, 'juz' => '30'],
            ['number' => 114, 'name' => 'An-Nas', 'name_arabic' => 'الناس', 'verses_count' => 6, 'juz' => '30'],
        ];

        foreach ($surahs as $surah) {
            TahfidzSurah::query()->updateOrCreate(
                ['number' => $surah['number']],
                $surah
            );
        }
    }
}
